const SYSTEM=`Ты — AI-консультант компании «ВК Реновация» в Санкт-Петербурге. Помогай пользователю сформировать идею ремонта и структурировать требования. Отвечай по-русски, ясно и профессионально. Не выдавай ориентировочные выводы за инженерное заключение, не обещай точную цену и не выдумывай факты о компании. Для скрытых дефектов, электрики, несущих конструкций, газа и влажности рекомендуй очное обследование специалистом. В конце ответа предлагай один полезный следующий шаг.`;
const MODE={chat:'Проведи консультацию по ремонту.',vision:'Проанализируй приложенное фото помещения: что видно, возможные риски, рекомендуемые работы и что нельзя определить по фото.',concept:'Составь интерьерную концепцию: идея, палитра, материалы, свет, мебель, практические ограничения.',brief:'Сформируй структурированное техническое задание: объект, цели, стиль, помещения, работы, материалы, бюджетные ограничения, вопросы для уточнения.'};
const contextText=c=>`Контекст: объект — ${c.objectType||'не указан'}; помещение — ${c.room||'не указано'}; стиль — ${c.style||'не указан'}; площадь — ${c.area||'не указана'}; бюджетный уровень — ${c.budget||'не указан'}.`;
const safeJson=async r=>{const t=await r.text();let j;try{j=JSON.parse(t)}catch{throw new Error(`Некорректный ответ провайдера (${r.status})`)}if(!r.ok)throw new Error(j?.error?.message||j?.detail||`Ошибка провайдера ${r.status}`);return j};
function dataUrl(image){if(!image)return null;if(!/^data:image\/(jpeg|png|webp);base64,/i.test(image))throw new Error('Неподдерживаемое изображение');return image}
function mimeAndData(url){const m=url.match(/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/i);return m?{mime:m[1],data:m[2]}:null}
function promptFor(body){return `${MODE[body.tool]||MODE.chat}\n${contextText(body.context||{})}\nЗапрос пользователя: ${body.prompt||'Проанализируй предоставленный контекст.'}`}
async function openai(body,env){const content=[{type:'text',text:promptFor(body)}];if(body.image)content.push({type:'image_url',image_url:{url:dataUrl(body.image)}});const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:env.OPENAI_CHAT_MODEL||'gpt-4.1-mini',messages:[{role:'system',content:SYSTEM},...(body.history||[]).slice(-10).map(x=>({role:x.role==='assistant'?'assistant':'user',content:String(x.content).slice(0,4000)})),{role:'user',content}],temperature:.5,max_tokens:1500})});const j=await safeJson(r);return{text:j.choices?.[0]?.message?.content||'Ответ не получен',provider:'openai',model:j.model}}
async function gemini(body,env){const parts=[{text:`${SYSTEM}\n${promptFor(body)}`}];const md=mimeAndData(body.image);if(md)parts.push({inline_data:{mime_type:md.mime,data:md.data}});const model=env.GEMINI_MODEL||'gemini-2.5-flash';const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${env.GEMINI_API_KEY}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts}],generationConfig:{temperature:.5,maxOutputTokens:1600}})});const j=await safeJson(r);return{text:j.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'Ответ не получен',provider:'gemini',model}}
async function anthropic(body,env){const content=[];const md=mimeAndData(body.image);if(md)content.push({type:'image',source:{type:'base64',media_type:md.mime,data:md.data}});content.push({type:'text',text:promptFor(body)});const model=env.ANTHROPIC_MODEL||'claude-sonnet-4-20250514';const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'x-api-key':env.ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01','content-type':'application/json'},body:JSON.stringify({model,system:SYSTEM,max_tokens:1600,messages:[...(body.history||[]).slice(-10).map(x=>({role:x.role==='assistant'?'assistant':'user',content:String(x.content).slice(0,4000)})),{role:'user',content}]})});const j=await safeJson(r);return{text:j.content?.filter(x=>x.type==='text').map(x=>x.text).join('\n')||'Ответ не получен',provider:'anthropic',model}}
async function custom(body,env){const base=(env.CUSTOM_OPENAI_BASE_URL||'').replace(/\/$/,'');const r=await fetch(`${base}/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${env.CUSTOM_OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:env.CUSTOM_OPENAI_MODEL,messages:[{role:'system',content:SYSTEM},{role:'user',content:promptFor(body)}],max_tokens:1500})});const j=await safeJson(r);return{text:j.choices?.[0]?.message?.content||'Ответ не получен',provider:'custom',model:j.model}}
function demo(body){const c=body.context||{},p=body.prompt||'';const base=body.tool==='vision'?`По демонстрационному анализу помещения «${c.room||'комната'}»:\n\n1. Сначала стоит проверить геометрию стен и пола, состояние электрики и признаки влаги.\n2. Для обновления пространства подойдут спокойная базовая палитра, несколько сценариев света и износостойкие материалы.\n3. По одной фотографии нельзя достоверно оценить скрытые коммуникации, несущие элементы и точный объём работ.\n\nСледующий шаг: сделайте фото каждой стены и укажите площадь помещения.`:body.tool==='concept'?`Концепция «${c.style||'Современный'}»: светлая нейтральная база, натуральные фактуры, тёплый локальный свет и один выразительный акцент. Для уровня «${c.budget||'Комфорт'}» разумно сосредоточить бюджет на напольном покрытии, освещении и столярных элементах.\n\nСледующий шаг: уточните, какие предметы мебели необходимо сохранить.`:body.tool==='brief'?`AI-БРИФ\nОбъект: ${c.objectType||'не указан'}\nПомещение: ${c.room||'не указано'}\nПлощадь: ${c.area||'уточнить'}\nСтиль: ${c.style||'уточнить'}\nБюджет: ${c.budget||'уточнить'}\nЗадача: ${p||'требует уточнения'}\n\nТребуется уточнить: сроки, состав семьи, существующие коммуникации и сохраняемую мебель.`:`Понял задачу: ${p||'нужна консультация по интерьеру'}. Для начала рекомендую зафиксировать площадь, текущее состояние, желаемый стиль и рамки бюджета. Затем можно подготовить перечень работ и визуальную концепцию.\n\nСледующий шаг: загрузите фото помещения или укажите его площадь.`;return{text:base,provider:'demo',model:'VK Demo AI'}}
async function generateOpenAI(body,env){
 const prompt=`Professional photorealistic interior design visualization. ${promptFor(body)}. Preserve plausible architecture, premium editorial lighting, no text, no watermark.`;
 const model=env.OPENAI_IMAGE_MODEL||'gpt-image-1';let r;
 if(body.image){
  const md=mimeAndData(body.image);if(!md)throw new Error('Некорректное исходное изображение');
  const form=new FormData();form.append('model',model);form.append('prompt',prompt);form.append('size','1536x1024');form.append('quality','medium');
  form.append('image',new Blob([Buffer.from(md.data,'base64')],{type:md.mime}),md.mime==='image/png'?'room.png':md.mime==='image/webp'?'room.webp':'room.jpg');
  r=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${env.OPENAI_API_KEY}`},body:form});
 }else{
  r=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{Authorization:`Bearer ${env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model,prompt,size:'1536x1024',quality:'medium',n:1})});
 }
 const j=await safeJson(r),d=j.data?.[0],url=d?.url||(d?.b64_json?`data:image/png;base64,${d.b64_json}`:null);if(!url)throw new Error('Провайдер не вернул изображение');return{url,provider:'openai',model};
}
async function generateFal(body,env,type='image'){const model=type==='video'?(env.FAL_VIDEO_MODEL||'fal-ai/kling-video/v2.1/master/image-to-video'):(env.FAL_IMAGE_MODEL||'fal-ai/flux-pro/v1.1');const input={prompt:promptFor(body)};if(body.image){if(type==='video')input.image_url=body.image;else input.image_url=body.image}const r=await fetch(`https://queue.fal.run/${model}`,{method:'POST',headers:{Authorization:`Key ${env.FAL_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(input)});const j=await safeJson(r);return{job:true,provider:'fal',type,requestId:j.request_id,statusUrl:j.status_url,responseUrl:j.response_url,model}}
async function generateReplicate(body,env,type='image'){const version=type==='video'?env.REPLICATE_VIDEO_VERSION:env.REPLICATE_IMAGE_VERSION;if(!version)throw new Error('Укажите версию модели Replicate в .env');const input={prompt:promptFor(body)};if(body.image)input.image=body.image;const r=await fetch('https://api.replicate.com/v1/predictions',{method:'POST',headers:{Authorization:`Bearer ${env.REPLICATE_API_TOKEN}`,'Content-Type':'application/json','Prefer':'wait=5'},body:JSON.stringify({version,input})});const j=await safeJson(r);return{job:true,provider:'replicate',type,id:j.id,status:j.status,url:j.urls?.get,output:j.output,model:version}}
async function pollJob(provider,body,env){if(provider==='fal'){const r=await fetch(body.statusUrl,{headers:{Authorization:`Key ${env.FAL_KEY}`}});const j=await safeJson(r);if(j.status==='COMPLETED'){const out=await safeJson(await fetch(body.responseUrl,{headers:{Authorization:`Key ${env.FAL_KEY}`}}));return{status:'succeeded',output:out}}return{status:(j.status||'processing').toLowerCase(),detail:j}}
if(provider==='replicate'){const r=await fetch(`https://api.replicate.com/v1/predictions/${encodeURIComponent(body.id)}`,{headers:{Authorization:`Bearer ${env.REPLICATE_API_TOKEN}`}});const j=await safeJson(r);return{status:j.status,output:j.output,error:j.error}}
throw new Error('Неизвестное задание')}
module.exports={openai,gemini,anthropic,custom,demo,generateOpenAI,generateFal,generateReplicate,pollJob};