const path=require('path'),fs=require('fs'),crypto=require('crypto');
const envFile=path.join(__dirname,'../.env');
if(fs.existsSync(envFile))for(const raw of fs.readFileSync(envFile,'utf8').split(/\r?\n/)){const line=raw.trim();if(!line||line.startsWith('#'))continue;const i=line.indexOf('=');if(i<1)continue;const k=line.slice(0,i).trim(),v=line.slice(i+1).trim().replace(/^(['"])(.*)\1$/,'$2');if(process.env[k]===undefined)process.env[k]=v}
const express=require('express'),P=require('./providers'),A=require('./admin-store');
const app=express(),PORT=process.env.PORT||3000,root=path.join(__dirname,'..'),pub=path.join(root,'public'),dataFile=path.join(root,'data/leads.json');
app.disable('x-powered-by');app.set('trust proxy',1);app.use(express.json({limit:'12mb'}));app.use(express.urlencoded({extended:false,limit:'1mb'}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Cross-Origin-Resource-Policy','same-origin');next()});
const hits=new Map(),jobs=new Map(),sessions=new Map(),limit=Number(process.env.MAX_REQUESTS_PER_10_MIN||30);function rate(req,res,next){const now=Date.now(),a=(hits.get(req.ip)||[]).filter(t=>now-t<600000);if(a.length>=limit)return res.status(429).json({error:'Слишком много запросов'});a.push(now);hits.set(req.ip,a);next()}
const configured=()=>{const s=A.getSecrets();return{demo:true,openai:!!s.OPENAI_API_KEY,gemini:!!s.GEMINI_API_KEY,anthropic:!!s.ANTHROPIC_API_KEY,fal:!!s.FAL_KEY,replicate:!!s.REPLICATE_API_TOKEN,custom:!!(s.CUSTOM_OPENAI_BASE_URL&&s.CUSTOM_OPENAI_API_KEY)}};
const capabilities={openai:['chat','vision','concept','brief','image'],gemini:['chat','vision','concept','brief'],anthropic:['chat','vision','concept','brief'],fal:['image','video'],replicate:['image','video'],custom:['chat'],demo:['chat','vision','concept','brief','image','video']};
function envWithSecrets(){return{...process.env,...A.getSecrets()}}function valid(b){if(!b||typeof b!=='object')throw Error('Пустой запрос');b.prompt=String(b.prompt||'').trim().slice(0,4000);b.tool=String(b.tool||'chat');if(b.image&&String(b.image).length>10000000)throw Error('Изображение слишком большое');return b}
app.get('/api/config',(req,res)=>res.json({providers:configured(),demoMode:process.env.DEMO_MODE!=='false',capabilities}));
app.post('/api/ai',rate,async(req,res)=>{try{const b=valid(req.body),p=b.provider||'demo',cfg=configured();if(!cfg[p])throw Error('Провайдер не настроен');if(!capabilities[p]?.includes(b.tool))throw Error('Эта модель не поддерживает задачу');const e=envWithSecrets();let out=p==='openai'?await P.openai(b,e):p==='gemini'?await P.gemini(b,e):p==='anthropic'?await P.anthropic(b,e):p==='custom'?await P.custom(b,e):P.demo(b);res.json(out)}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/generate',rate,async(req,res)=>{try{const b=valid(req.body),p=b.provider||'demo',type=String(b.type||''),e=envWithSecrets();if(!['image','video'].includes(type)||!configured()[p])throw Error('Неподдерживаемая генерация');let out=p==='openai'&&type==='image'?await P.generateOpenAI(b,e):p==='fal'?await P.generateFal(b,e,type):p==='replicate'?await P.generateReplicate(b,e,type):{demo:true,type,url:type==='image'?'/assets/img/original/work-3.jpg':null,text:'Демо-режим: добавьте ключ провайдера для генерации.'};if(out.job){const jobId=crypto.randomUUID();jobs.set(jobId,{...out,createdAt:Date.now()});return res.json({job:true,jobId,provider:out.provider,type:out.type})}res.json(out)}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/jobs/status',rate,async(req,res)=>{try{const id=String(req.body.jobId),j=jobs.get(id);if(!j)throw Error('Задание не найдено');const out=await P.pollJob(j.provider,j,envWithSecrets());if(['succeeded','completed','failed','canceled'].includes(out.status))jobs.delete(id);res.json(out)}catch(e){res.status(400).json({error:e.message})}});
function adminAuth(req,res,next){const sid=req.headers.cookie?.match(/vk_admin=([^;]+)/)?.[1];if(!sid||!sessions.has(sid))return res.status(401).json({error:'Требуется вход'});req.admin=sessions.get(sid);next()}
function adminLogin(req,res){const u=process.env.ADMIN_USERNAME||'admin',hash=process.env.ADMIN_PASSWORD_HASH;if(!hash)return res.status(503).json({error:'Сначала задайте ADMIN_PASSWORD_HASH и ADMIN_SESSION_SECRET'});const supplied=String(req.body.password||''),candidate=crypto.scryptSync(supplied,'vk-admin-salt',64).toString('hex');if(req.body.username!==u||candidate!==hash)return res.status(401).json({error:'Неверные данные'});const sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,{username:u,createdAt:Date.now()});res.setHeader('Set-Cookie',`vk_admin=${sid}; HttpOnly; SameSite=Strict; Secure=${req.secure?'true':'false'}; Path=/; Max-Age=28800`);res.json({ok:true})}
app.post('/api/admin/login',rate,adminLogin);app.post('/api/admin/logout',(req,res)=>{const sid=req.headers.cookie?.match(/vk_admin=([^;]+)/)?.[1];if(sid)sessions.delete(sid);res.setHeader('Set-Cookie','vk_admin=; Max-Age=0; Path=/');res.json({ok:true})});
app.get('/api/admin/me',adminAuth,(req,res)=>res.json({ok:true,username:req.admin.username}));
app.get('/api/admin/secrets',adminAuth,(req,res)=>res.json(A.statuses()));
app.post('/api/admin/secrets',adminAuth,(req,res)=>{try{A.updateSecrets(req.body||{});res.json({ok:true,secrets:A.statuses()})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/admin/leads',adminAuth,(req,res)=>{try{res.json(JSON.parse(fs.readFileSync(dataFile,'utf8')))}catch{res.json([])}});
app.get('/api/admin/content',adminAuth,(req,res)=>res.json(A.read(A.contentFile,{})));
app.put('/api/admin/content',adminAuth,(req,res)=>{A.save(A.contentFile,req.body||{});res.json({ok:true})});
app.post('/api/leads',rate,async(req,res)=>{try{const b=req.body||{};if(b.website)return res.json({ok:true});if(!b.name||!b.phone||b.consent!=='on')throw Error('Заполните имя, телефон и подтвердите согласие');const lead={id:crypto.randomUUID(),createdAt:new Date().toISOString(),consentVersion:'2026-08-30',consentAt:new Date().toISOString(),name:String(b.name).slice(0,100),phone:String(b.phone).slice(0,50),email:String(b.email||'').slice(0,150),service:String(b.service||b.type||'').slice(0,100),message:String(b.message||'').slice(0,1200),sessionId:String(b.sessionId||'').slice(0,100)};const a=(()=>{try{return JSON.parse(fs.readFileSync(dataFile,'utf8'))}catch{return[]}})();a.push(lead);fs.writeFileSync(dataFile,JSON.stringify(a,null,2));res.status(201).json({ok:true,id:lead.id})}catch(e){res.status(400).json({error:e.message})}});
app.use(express.static(pub,{index:false,maxAge:'1h',setHeaders:(res,file)=>{if(/\.(?:js|css|svg|webp|jpe?g|png|mp4|woff2?)$/i.test(file))res.setHeader('Cache-Control','public, max-age=86400, immutable')}}));app.get('/robots.txt',(req,res)=>res.sendFile(path.join(pub,'robots.txt')));app.get('/sitemap.xml',(req,res)=>res.type('application/xml').sendFile(path.join(pub,'sitemap.xml')));app.get('/',(req,res)=>res.sendFile(path.join(pub,'preloader.html')));app.get(['/main','/index.html'],(req,res)=>res.sendFile(path.join(pub,'index.html')));app.get(['/ai','/ai/'],(req,res)=>res.sendFile(path.join(pub,'ai/index.html')));app.get(['/admin','/admin/'],(req,res)=>res.sendFile(path.join(pub,'admin/index.html')));app.listen(PORT,'0.0.0.0',()=>console.log(`VK Renovation admin build: http://localhost:${PORT}`));
